# games-multiplayer-bringup.tf
#
# Everything the multiplayer platform needs besides the AWS resources in
# games-multiplayer.tf, done by ONE `terraform apply` on the jumpbox:
#
#   secrets      generated here (random provider) and written to Secrets Manager and Vercel
#   images       built by CodeBuild from the pinned games-repo commit, before any task
#                definition names them
#   Vercel env   the MP_* settings and secrets on the colton-games project (Production and
#                Preview), the automation bypass, OIDC in Team issuer mode, and Preview's
#                Supabase connection
#   Supabase     the pinned mp migration, applied once over certificate-verified TLS
#   verified     the apply waits for the new router deployment, a healthy target and a
#                200 `ok` from https://play.cc-games.app/healthz, and fails otherwise
#
# The steps that are not plain resources are terraform_data local-execs running
# games-multiplayer/bringup.py on the jumpbox with its administrator role. Each one checks
# live state first, changes only what is missing, verifies, and exits non-zero on failure.
# They re-run only when their inputs change (the source commit, the image tags, ...), so a
# second apply with nothing changed is an empty plan.
#
# SECRETS ARE IN TERRAFORM STATE. The token key, MP_TEST_KEY, CRON_SECRET, the cookie
# secrets, Preview's Skyhook secret and the automation bypass are generated by the random
# provider, so their values are stored in state: the S3 backend (ejc3-terraform-state) is
# encrypted, versioned, and readable only by administration, which is the same boundary as
# the Secrets Manager copies. What is NOT in state: the Vercel API token and GitHub PAT
# (read by bringup.py at apply time), the Supabase database URL, and the Supabase values
# copied to Preview (both read from Vercel's API into memory and never written to disk).
#
# Terraform is pinned to 1.10.3, so write-only arguments (value_wo, 1.11+) are not an
# option for keeping these out of state.

variable "games_mp_token_kids" {
  description = "Token key ids, newest first. The first signs, all verify. Rotate: prepend a new id, apply, redeploy production, then drop the old id and apply."
  type        = list(string)
  default     = ["kid1"]

  validation {
    condition = (
      length(var.games_mp_token_kids) > 0 &&
      length(distinct(var.games_mp_token_kids)) == length(var.games_mp_token_kids) &&
      alltrue([for k in var.games_mp_token_kids : can(regex("^[A-Za-z0-9_-]{1,32}$", k))])
    )
    error_message = "games_mp_token_kids must be distinct ids of 1-32 characters from [A-Za-z0-9_-]."
  }
}

variable "games_mp_preview_supabase_sync" {
  description = "Bump to re-copy the Supabase URL and server key from Production to Preview (e.g. after the integration rotates its keys)."
  type        = string
  default     = "1"
}

variable "games_mp_migrate" {
  description = "Apply the pinned mp Supabase migration during apply. false skips the step entirely."
  type        = bool
  default     = true
}

locals {
  games_mp_repo      = "CoderColton/colton-games"
  games_mp_bringup   = "${path.module}/games-multiplayer/bringup.py"
  games_mp_cache_dir = "${path.module}/.terraform/games-mp"
  games_mp_migration = "supabase/migrations/20260926000000_mp.sql"

  # MP_TOKEN_KEYS: kid:<base64 32 bytes>, first signs. The router gets it from Secrets
  # Manager, the lobby from Vercel; both are written from this one value.
  games_mp_token_keys = join(",", [
    for kid in var.games_mp_token_kids : "${kid}:${random_bytes.games_mp_token_key[kid].base64}"
  ])

  # Exactly the tags the task definitions run; CodeBuild must produce these.
  games_mp_expected_images = merge(
    { "games/mp-router" = local.mp_router_tag },
    { for id, tag in local.mp_engine_tags : "games/${id}-engine" => tag },
  )
}

# -------------------------------------------------------------------------------------
# Generated secrets
# -------------------------------------------------------------------------------------

resource "random_bytes" "games_mp_token_key" {
  for_each = toset(var.games_mp_token_kids)
  length   = 32
}

# MP_TEST_KEY opens the hidden `mptest` game in production (x-mp-test-key); the remote e2e
# driver needs it: `terraform output -raw games_mp_test_key`.
resource "random_password" "games_mp_test_key" {
  length  = 40
  special = false
}

# CRON_SECRET guards GET /api/mp/sweep (Vercel cron sends it as a bearer token).
resource "random_password" "games_mp_cron_secret" {
  length  = 48
  special = false
}

# MP_COOKIE_SECRET signs the guest id cookie. One per environment. Production's own copy is
# needed because the lobby's fallback, SKYHOOK_LEADERBOARD_SECRET, exists only in
# Development today. Replacing it resets every guest identity, so it has no keepers.
resource "random_password" "games_mp_cookie_secret" {
  for_each = toset(["production", "preview"])
  length   = 64
  special  = false
}

# Preview's own Skyhook signing key: previews share the database but never production's key.
resource "random_password" "games_mp_skyhook_preview_secret" {
  length  = 64
  special = false
}

# Vercel requires exactly 32 alphanumerics for an automation bypass secret.
resource "random_password" "games_mp_bypass" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret_version" "games_mp_token_keys" {
  secret_id     = aws_secretsmanager_secret.games_mp_token_keys.id
  secret_string = local.games_mp_token_keys
}

resource "aws_secretsmanager_secret" "games_mp_test_key" {
  name                    = "games/mp-test-key"
  description             = "MP_TEST_KEY: opens hidden multiplayer games in production. Generated by Terraform."
  recovery_window_in_days = 7
  tags                    = { Name = "games/mp-test-key", Managed = "terraform", Project = "games-multiplayer" }
}

resource "aws_secretsmanager_secret_version" "games_mp_test_key" {
  secret_id     = aws_secretsmanager_secret.games_mp_test_key.id
  secret_string = random_password.games_mp_test_key.result
}

resource "aws_secretsmanager_secret" "games_mp_cron_secret" {
  name                    = "games/mp-cron-secret"
  description             = "CRON_SECRET for the lobby's /api/mp/sweep. Generated by Terraform."
  recovery_window_in_days = 7
  tags                    = { Name = "games/mp-cron-secret", Managed = "terraform", Project = "games-multiplayer" }
}

resource "aws_secretsmanager_secret_version" "games_mp_cron_secret" {
  secret_id     = aws_secretsmanager_secret.games_mp_cron_secret.id
  secret_string = random_password.games_mp_cron_secret.result
}

# FALLBACK ONLY, container only. bringup.py migrate first reads the Supabase integration's
# POSTGRES_URL_NON_POOLING from the Vercel project (Production) at apply time. Only if
# Vercel will not decrypt it does it read this secret, whose value EJ sets once:
#   printf '%s' 'postgres://...' | aws secretsmanager put-secret-value --region us-west-1 \
#     --secret-id games/supabase-db-url --secret-string file:///dev/stdin
resource "aws_secretsmanager_secret" "games_supabase_db_url" {
  name                    = "games/supabase-db-url"
  description             = "Fallback Postgres URL for the games Supabase project (mp migration). Value set outside Terraform, only if Vercel cannot provide it."
  recovery_window_in_days = 7
  tags                    = { Name = "games/supabase-db-url", Managed = "terraform", Project = "games-multiplayer" }
}

resource "aws_secretsmanager_secret_policy" "games_mp_admin_only" {
  for_each = {
    test_key    = aws_secretsmanager_secret.games_mp_test_key.arn
    cron_secret = aws_secretsmanager_secret.games_mp_cron_secret.arn
    db_url      = aws_secretsmanager_secret.games_supabase_db_url.arn
  }
  secret_arn = each.value
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "OnlyAdministrationCanRead"
      Effect    = "Deny"
      Principal = "*"
      Action    = "secretsmanager:GetSecretValue"
      Resource  = each.value
      Condition = { ArnNotLike = { "aws:PrincipalArn" = local.games_mp_admin_principals } }
    }]
  })
}

# -------------------------------------------------------------------------------------
# Image builds: CodeBuild from an S3 copy of the pinned commit
# -------------------------------------------------------------------------------------
#
# SOURCE. CoderColton/colton-games is private. The build does NOT get a GitHub credential:
# the jumpbox (bringup.py build) downloads the pinned commit with the existing read
# credential `github-pat-ejc3`, repacks it, and uploads it to this bucket; CodeBuild reads
# only that object. Rejected alternatives:
#   - CodeBuild's own GitHub source with the PAT (source auth SECRETS_MANAGER): the build
#     runs the games repo's code, which could then read ejc3's PAT through the build role.
#   - a CodeConnections GitHub connection: it starts PENDING until someone completes a
#     browser handshake and installs the AWS Connector app on CoderColton, which ejc3 (a
#     collaborator, not the owner) cannot approve. Two human steps, forever in the loop.
#   - the repo's `github` provider token: it is the webhook-admin PAT for ejc3's repos and
#     cannot read CoderColton's.

resource "aws_s3_bucket" "games_mp_build" {
  bucket = "games-mp-build-${data.aws_caller_identity.current.account_id}"
  tags   = { Name = "games-mp-build", Project = "games-multiplayer" }
}

resource "aws_s3_bucket_public_access_block" "games_mp_build" {
  bucket                  = aws_s3_bucket.games_mp_build.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "games_mp_build" {
  bucket = aws_s3_bucket.games_mp_build.id
  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

# Sources are only needed for the build that uses them.
resource "aws_s3_bucket_lifecycle_configuration" "games_mp_build" {
  bucket = aws_s3_bucket.games_mp_build.id
  rule {
    id     = "expire-sources"
    status = "Enabled"
    filter { prefix = "sources/" }
    expiration { days = 30 }
    abort_incomplete_multipart_upload { days_after_initiation = 1 }
  }
}

resource "aws_s3_bucket_policy" "games_mp_build" {
  bucket = aws_s3_bucket.games_mp_build.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "DenyInsecureTransport"
      Effect    = "Deny"
      Principal = "*"
      Action    = "s3:*"
      Resource  = [aws_s3_bucket.games_mp_build.arn, "${aws_s3_bucket.games_mp_build.arn}/*"]
      Condition = { Bool = { "aws:SecureTransport" = "false" } }
    }]
  })
  depends_on = [aws_s3_bucket_public_access_block.games_mp_build]
}

resource "aws_cloudwatch_log_group" "games_mp_codebuild" {
  name              = "/aws/codebuild/games-mp-images"
  retention_in_days = 14
}

resource "aws_iam_role" "games_mp_codebuild" {
  name = "games-mp-codebuild"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "codebuild.amazonaws.com" }
      Action    = "sts:AssumeRole"
      Condition = {
        StringEquals = { "aws:SourceAccount" = data.aws_caller_identity.current.account_id }
        ArnLike      = { "aws:SourceArn" = "arn:aws:codebuild:${var.aws_region}:${data.aws_caller_identity.current.account_id}:project/games-mp-images" }
      }
    }]
  })
  tags = { Name = "games-mp-codebuild", Project = "games-multiplayer" }
}

# Least privilege: read the uploaded sources, write its own logs, push to the games
# repositories. No Secrets Manager, no GitHub credential, no ECS, no IAM.
resource "aws_iam_role_policy" "games_mp_codebuild" {
  name = "build-and-push-games-images"
  role = aws_iam_role.games_mp_codebuild.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid      = "ReadSources"
        Effect   = "Allow"
        Action   = ["s3:GetObject", "s3:GetObjectVersion"]
        Resource = "${aws_s3_bucket.games_mp_build.arn}/sources/*"
      },
      {
        Sid      = "LocateSourceBucket"
        Effect   = "Allow"
        Action   = ["s3:GetBucketAcl", "s3:GetBucketLocation"]
        Resource = aws_s3_bucket.games_mp_build.arn
      },
      {
        Sid      = "Logs"
        Effect   = "Allow"
        Action   = ["logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = "${aws_cloudwatch_log_group.games_mp_codebuild.arn}:*"
      },
      {
        Sid      = "EcrLogin"
        Effect   = "Allow"
        Action   = "ecr:GetAuthorizationToken"
        Resource = "*"
      },
      {
        Sid    = "PushGamesImages"
        Effect = "Allow"
        Action = [
          "ecr:BatchCheckLayerAvailability", "ecr:BatchGetImage", "ecr:CompleteLayerUpload",
          "ecr:DescribeImages", "ecr:GetDownloadUrlForLayer", "ecr:InitiateLayerUpload",
          "ecr:PutImage", "ecr:UploadLayerPart",
        ]
        Resource = [for repo in aws_ecr_repository.games_mp : repo.arn]
      },
    ]
  })
}

# Smallest ARM compute (2 vCPU / 4 GB), native arm64 builds for Fargate ARM64. Privileged
# because the build runs docker. Node 24 comes from the image's runtime-versions.
resource "aws_codebuild_project" "games_mp_images" {
  name          = "games-mp-images"
  description   = "Builds and pushes the games multiplayer images from a pinned colton-games commit"
  service_role  = aws_iam_role.games_mp_codebuild.arn
  build_timeout = 30

  artifacts {
    type = "NO_ARTIFACTS"
  }

  environment {
    type                        = "ARM_CONTAINER"
    compute_type                = "BUILD_GENERAL1_SMALL"
    image                       = "aws/codebuild/amazonlinux-aarch64-standard:4.0"
    image_pull_credentials_type = "CODEBUILD"
    privileged_mode             = true

    environment_variable {
      name  = "ACCOUNT_ID"
      value = data.aws_caller_identity.current.account_id
    }
  }

  # Each build overrides the location with sources/<commit>.zip.
  source {
    type      = "S3"
    location  = "${aws_s3_bucket.games_mp_build.bucket}/sources/pinned.zip"
    buildspec = file("${path.module}/games-multiplayer/buildspec.yml")
  }

  logs_config {
    cloudwatch_logs {
      group_name = aws_cloudwatch_log_group.games_mp_codebuild.name
    }
  }

  tags = { Name = "games-mp-images", Project = "games-multiplayer" }
}

# Runs once per set of expected tags. Skips CodeBuild entirely when ECR already has them.
resource "terraform_data" "games_mp_build" {
  count = var.games_mp_build ? 1 : 0

  triggers_replace = {
    ref       = var.games_mp_source_ref
    images    = jsonencode(local.games_mp_expected_images)
    project   = aws_codebuild_project.games_mp_images.arn
    buildspec = filesha256("${path.module}/games-multiplayer/buildspec.yml")
  }

  provisioner "local-exec" {
    command = "python3 ${local.games_mp_bringup} build --region ${var.aws_region} --ref ${var.games_mp_source_ref} --repo ${local.games_mp_repo} --project ${aws_codebuild_project.games_mp_images.name} --bucket ${aws_s3_bucket.games_mp_build.bucket} --cache-dir ${local.games_mp_cache_dir} --expect \"$GAMES_MP_EXPECT\""
    environment = {
      GAMES_MP_EXPECT = jsonencode(local.games_mp_expected_images)
    }
  }

  depends_on = [
    aws_iam_role_policy.games_mp_codebuild,
    aws_ecr_repository.games_mp,
    aws_s3_bucket_policy.games_mp_build,
  ]
}

# -------------------------------------------------------------------------------------
# Vercel: env, automation bypass, OIDC issuer mode, Preview's Supabase
# -------------------------------------------------------------------------------------
#
# Only the multiplayer set below is managed here; every other env var of the project stays
# managed in Vercel (vercel-cc-games.tf). Env changes reach a deployment only when it is
# (re)built, so they take effect on the next production deploy and on new previews.
#
# Production and Preview get the same settings, except:
#   MP_ENV   production / preview (the lobby requires MP_ENV == VERCEL_ENV)
#   MP_API   production only: https://cc-games.app. Preview derives https://$VERCEL_URL per
#            deployment, so engines call back the preview that launched them.
#   Preview only: SKYHOOK_LEADERBOARD_ENVIRONMENT=preview and its own Skyhook key, because
#            Preview now shares the Supabase database (rows are scoped by environment).
# Development gets nothing: local development uses MP_LAUNCHER=local, and the launcher
# role and the router trust only production and preview.

locals {
  games_mp_vercel_shared_config = {
    MP_ROLE_ARN = aws_iam_role.games_mp_launcher.arn
    # Vercel's own convention; the lobby reads MP_ROLE_ARN first and falls back to this.
    AWS_ROLE_ARN = aws_iam_role.games_mp_launcher.arn
    MP_CLUSTER   = aws_ecs_cluster.games.name
    MP_SUBNETS   = join(",", [for s in local.mp_subnets : s.id])
    MP_ENGINE_SG = aws_security_group.games_engine.id
    MP_REGION    = var.aws_region
    # Pins the AWS SDK's region; Vercel otherwise sets AWS_REGION to the function's own
    # region, which can move (https://vercel.com/docs/oidc/aws).
    AWS_REGION      = var.aws_region
    MP_LAUNCHER     = "ecs"
    MP_PUBLIC_ENTRY = "wss://${local.mp_play_domain}"
  }

  # "<KEY>" targets both environments; "<KEY>/<env>" targets one. Sensitive values stay out
  # of this map (for_each keys and metadata must not be sensitive); they are looked up from
  # games_mp_vercel_secret_values by the same name.
  games_mp_vercel_env = merge(
    { for k, v in local.games_mp_vercel_shared_config : k => { targets = ["production", "preview"], sensitive = false, value = v } },
    {
      "MP_ENV/production"                       = { targets = ["production"], sensitive = false, value = "production" }
      "MP_ENV/preview"                          = { targets = ["preview"], sensitive = false, value = "preview" }
      "MP_API/production"                       = { targets = ["production"], sensitive = false, value = "https://cc-games.app" }
      "SKYHOOK_LEADERBOARD_ENVIRONMENT/preview" = { targets = ["preview"], sensitive = false, value = "preview" }
      "MP_TOKEN_KEYS"                           = { targets = ["production", "preview"], sensitive = true, value = null }
      "MP_TEST_KEY"                             = { targets = ["production", "preview"], sensitive = true, value = null }
      "CRON_SECRET"                             = { targets = ["production", "preview"], sensitive = true, value = null }
      "MP_COOKIE_SECRET/production"             = { targets = ["production"], sensitive = true, value = null }
      "MP_COOKIE_SECRET/preview"                = { targets = ["preview"], sensitive = true, value = null }
      "SKYHOOK_LEADERBOARD_SECRET/preview"      = { targets = ["preview"], sensitive = true, value = null }
    },
  )

  games_mp_vercel_secret_values = {
    "MP_TOKEN_KEYS"                      = local.games_mp_token_keys
    "MP_TEST_KEY"                        = random_password.games_mp_test_key.result
    "CRON_SECRET"                        = random_password.games_mp_cron_secret.result
    "MP_COOKIE_SECRET/production"        = random_password.games_mp_cookie_secret["production"].result
    "MP_COOKIE_SECRET/preview"           = random_password.games_mp_cookie_secret["preview"].result
    "SKYHOOK_LEADERBOARD_SECRET/preview" = random_password.games_mp_skyhook_preview_secret.result
  }
}

resource "vercel_project_environment_variable" "games_mp" {
  for_each = local.games_mp_vercel_env

  team_id    = var.vercel_team_id
  project_id = local.colton_games_vercel_project_id
  key        = split("/", each.key)[0]
  value      = each.value.sensitive ? local.games_mp_vercel_secret_values[each.key] : each.value.value
  target     = each.value.targets
  sensitive  = each.value.sensitive
  comment    = "games multiplayer; managed by ejc3/aws games-multiplayer-bringup.tf"
}

# Deployment Protection covers every preview. Engines launched by a preview lobby call back
# its protected URL, and the remote e2e driver drives previews, so both present this
# secret as x-vercel-protection-bypass. is_env_var exposes it to deployments as
# VERCEL_AUTOMATION_BYPASS_SECRET; the lobby hands it to engines as MP_API_BYPASS.
resource "vercel_project_protection_bypass" "games_mp" {
  team_id    = var.vercel_team_id
  project_id = local.colton_games_vercel_project_id
  secret     = random_password.games_mp_bypass.result
  is_env_var = true
  note       = "games multiplayer: engine callbacks and remote e2e (ejc3/aws)"
}

# OIDC Team issuer mode. The provider can set oidc_token_config only on a whole
# vercel_project resource, which would mean importing the project and letting Terraform own
# every one of its settings. This step instead GETs the project, PATCHes only
# oidcTokenConfig if it is not already {enabled, team}, and verifies with a second GET.
# (It was already on in Team mode on 2026-09-27; the step keeps it that way.)
resource "terraform_data" "games_mp_vercel_oidc" {
  triggers_replace = {
    project = local.colton_games_vercel_project_id
    mode    = "team"
  }

  provisioner "local-exec" {
    command = "python3 ${local.games_mp_bringup} vercel-oidc --region ${var.aws_region} --team-id ${var.vercel_team_id} --project-id ${local.colton_games_vercel_project_id}"
  }
}

# Preview's Supabase connection. The integration (store_XlZp0ZAQE6nghCEU) is connected to
# Production and Development only. Vercel's API has no documented call to add an
# environment to an EXISTING integration connection (only "connect resource to project",
# whose effect on the live Production connection is undocumented), so this step copies the
# two values the lobby and Skyhook read, SUPABASE_URL and SUPABASE_SECRET_KEY, from
# Production into Preview-only variables. It never writes a variable that reaches
# Production or Development, and refuses if one with the same key spans Preview and
# another environment. The values pass through memory only: not in config, not in state.
# If the integration rotates its keys, bump var.games_mp_preview_supabase_sync.
resource "terraform_data" "games_mp_preview_supabase" {
  triggers_replace = {
    project = local.colton_games_vercel_project_id
    keys    = "SUPABASE_URL:encrypted,SUPABASE_SECRET_KEY:sensitive"
    sync    = var.games_mp_preview_supabase_sync
  }

  provisioner "local-exec" {
    command = "python3 ${local.games_mp_bringup} preview-supabase --region ${var.aws_region} --team-id ${var.vercel_team_id} --project-id ${local.colton_games_vercel_project_id} --keys SUPABASE_URL:encrypted,SUPABASE_SECRET_KEY:sensitive"
  }
}

# -------------------------------------------------------------------------------------
# Supabase migration
# -------------------------------------------------------------------------------------
#
# Runs on the jumpbox with psql (installed there on first use if missing), not in CodeBuild:
# the database URL then never has to be stored anywhere a build can read it, and the
# jumpbox reaches Supabase over IPv4 and IPv6 alike. The step:
#   - takes the migration file from the SAME pinned commit as the images;
#   - connects with sslmode=verify-full against the Supabase Root 2021 CA committed next to
#     it (fingerprint pinned in bringup.py);
#   - reads mp_private.schema_revision and does nothing when it is already at the file's
#     revision; refuses a partial or out-of-order state instead of guessing;
#   - runs only that one file (which never names skyhook_private or site_private, checked),
#     then verifies the revision.
# With no URL from Vercel and none in games/supabase-db-url, it FAILS the apply with the
# exact instruction; that is the one prerequisite a human may have to supply. A failed
# step is retried by the next apply (Terraform re-creates a tainted resource).
resource "terraform_data" "games_mp_migration" {
  count = var.games_mp_migrate ? 1 : 0

  triggers_replace = {
    ref  = var.games_mp_source_ref
    file = local.games_mp_migration
  }

  provisioner "local-exec" {
    command = "python3 ${local.games_mp_bringup} migrate --region ${var.aws_region} --team-id ${var.vercel_team_id} --project-id ${local.colton_games_vercel_project_id} --ref ${var.games_mp_source_ref} --repo ${local.games_mp_repo} --cache-dir ${local.games_mp_cache_dir} --file ${local.games_mp_migration} --ca ${path.module}/games-multiplayer/supabase-root-2021-ca.crt --url-secret ${aws_secretsmanager_secret.games_supabase_db_url.name}"
  }

  depends_on = [aws_secretsmanager_secret_policy.games_mp_admin_only]
}

# -------------------------------------------------------------------------------------
# Verification
# -------------------------------------------------------------------------------------
#
# After every router change: waits until the service's PRIMARY deployment runs this task
# definition and ECS reports the rollout COMPLETED (a circuit-breaker rollback FAILS the
# apply rather than passing on the old version), a target is healthy, and GET /healthz
# answers 200 `ok` over TLS with the certificate verified for play.cc-games.app. Bounded:
# 15 minutes, then it fails loudly.
resource "terraform_data" "games_mp_healthy" {
  count = local.mp_router_enabled ? 1 : 0

  triggers_replace = {
    task_definition = aws_ecs_task_definition.games_mp_router[0].arn
    token_keys      = sha256(local.games_mp_token_keys)
  }

  provisioner "local-exec" {
    command = "python3 ${local.games_mp_bringup} wait-healthy --region ${var.aws_region} --cluster ${aws_ecs_cluster.games.name} --service ${aws_ecs_service.games_mp_router[0].name} --task-definition-arn ${aws_ecs_task_definition.games_mp_router[0].arn} --target-group-arn ${aws_lb_target_group.games_mp_router.arn} --alb-dns ${aws_lb.games_play.dns_name} --host ${local.mp_play_domain}"
  }

  depends_on = [
    aws_ecs_service.games_mp_router,
    aws_lb_listener.games_play_https,
    cloudflare_dns_record.games_play,
  ]
}

# -------------------------------------------------------------------------------------
# Outputs for the remote e2e driver (sensitive: shown only with -raw / -json)
# -------------------------------------------------------------------------------------

output "games_mp_test_key" {
  description = "MP_TEST_KEY for the remote e2e run against production: terraform output -raw games_mp_test_key"
  value       = random_password.games_mp_test_key.result
  sensitive   = true
}

output "games_mp_cron_secret" {
  description = "CRON_SECRET, for an authorised /api/mp/sweep in the remote e2e run"
  value       = random_password.games_mp_cron_secret.result
  sensitive   = true
}

output "games_mp_automation_bypass_secret" {
  description = "x-vercel-protection-bypass value for driving preview deployments"
  value       = random_password.games_mp_bypass.result
  sensitive   = true
}
