# The Macs dial OUT to fcvm-metal-arm. These aliases consume its loopback-only
# reverse forwards; they do not open an AWS security-group port or start a tunnel.
# The existing ~/.ssh/to-mac private key stays on the persistent ARM root.
locals {
  mac_reverse_tunnel_setup = <<-MACSETUP
install -d -m 700 -o ubuntu -g ubuntu /home/ubuntu/.ssh

cat > /home/ubuntu/.ssh/config.d-mac-tunnels <<'MACCONFIG'
# Generated by Terraform (mac-reverse-tunnels.tf).
Host mac
    HostName 127.0.0.1
    Port 2222
    User ejcampbell
    IdentityFile ~/.ssh/to-mac

Host macbook
    HostName 127.0.0.1
    Port 2223
    User ejcampbell
    IdentityFile ~/.ssh/to-mac
    IdentitiesOnly yes
    HostKeyAlias ejs-macbook-pro-via-fcvm
    UserKnownHostsFile ~/.ssh/known_hosts.mac-tunnels
    StrictHostKeyChecking yes
    ServerAliveInterval 30
    ServerAliveCountMax 3
MACCONFIG

# Public host identity read directly from EJ's MacBook Pro when its tunnel was set up.
cat > /home/ubuntu/.ssh/known_hosts.mac-tunnels <<'MACHOSTKEYS'
ejs-macbook-pro-via-fcvm ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAX5Q08R6QP8SbnpXPZTKTwGgrLz4DnGMZzRw2EDGaxn
MACHOSTKEYS

# Include first so an old Host * cannot override a managed destination. Migrate only
# the two standalone hand-written stanzas; preserve unrelated hosts and includes.
python3 - <<'MACMIGRATE'
from pathlib import Path
import os
import shlex
import tempfile

path = Path('/home/ubuntu/.ssh/config')
original = path.read_text() if path.exists() else ''
include = 'Include ~/.ssh/config.d-mac-tunnels'
kept = []
skip = False
for line in original.splitlines(keepends=True):
    fields = shlex.split(line, comments=True)
    if fields and fields[0].lower() in ('host', 'match'):
        skip = (fields[0].lower() == 'host' and len(fields) == 2
                and fields[1] in ('mac', 'macbook'))
    if not skip and line.strip() != include:
        kept.append(line)
updated = include + '\n\n' + ''.join(kept).lstrip('\n')
if updated != original:
    backup = path.with_name('config.before-mac-tunnels')
    if path.exists() and not backup.exists():
        backup.write_text(original)
        backup.chmod(0o600)
    with tempfile.NamedTemporaryFile(mode='w', dir=path.parent, delete=False) as f:
        f.write(updated)
        temporary = f.name
    os.replace(temporary, path)
MACMIGRATE

chown ubuntu:ubuntu /home/ubuntu/.ssh/config /home/ubuntu/.ssh/config.d-mac-tunnels /home/ubuntu/.ssh/known_hosts.mac-tunnels
chmod 600 /home/ubuntu/.ssh/config /home/ubuntu/.ssh/config.d-mac-tunnels /home/ubuntu/.ssh/known_hosts.mac-tunnels
MACSETUP
}

output "mac_reverse_tunnel_usage" {
  description = "SSH back to the Macs while their outbound tunnels are connected"
  value       = "from fcvm-arm as ubuntu: ssh mac (127.0.0.1:2222) | ssh macbook (127.0.0.1:2223)"
}
