# wbox.tf
#
# THE WINDOWS BOX: one Windows Server 2025 instance with an NVIDIA GPU, for playtesting
# Windows games (first: Age of Empires I: Definitive Edition from the Microsoft Store, which
# needs the Xbox app and has no cloud-streaming version).
#
# PERSISTENT, unlike the GPU test box (gpu-box.tf): an installed game, its store login and
# its saves must survive, so terraform owns the instance and a separate 100 GB game disk
# (D:), and the dev boxes STOP and START it (`wbox up` / `wbox down`, scripts/wbox.sh) with
# a grant scoped to this one instance. Stopped, it costs only its disks (~$13/month);
# running, g4dn.xlarge with Windows is ~$0.82/hour in us-west-1. Its own copy of the
# dev-auto-stop Lambda (below) stops it after ONE hour below 5% CPU, checked every 10 minutes.
#
# REACHABLE ONLY FROM THE DEV BOXES (the perimeter rule: nothing new listens on the
# internet). Its security group admits RDP (3389) and Amazon DCV (8443, TCP and UDP) from
# the dev fleet's subnets only, so a player reaches it through a dev box: DCV's web client in
# a dev box's browser (the browser-manager desktops on fcvm-metal-arm), or a tunnel over the
# SSH already allowed, `ssh -L 8443:<wbox private IP>:8443 fcvm-arm`. It has its own subnet
# whose route table has the internet and nothing else -- no I/O-box peer route -- so a
# Windows desktop that runs downloaded games cannot reach the fleet's NFS scratch.
#
# FIRST BOOT (user_data, retried at each boot until it completes once): sets the Administrator
# password from Secrets Manager (wbox/administrator-password, generated here; the dev roles may
# read it), finds the game disk by its EBS volume id and formats it only if RAW, installs the
# NVIDIA GRID driver from AWS's bucket, Amazon DCV and Media Foundation, then reboots. The
# store and game installs are the player's.

variable "enable_wbox" {
  description = "Create the Windows playtest box (wbox.tf). The game disk has prevent_destroy either way."
  type        = bool
  default     = true
}

locals {
  wbox_name = "wbox"
  wbox_type = "g4dn.xlarge"
  # us-west-1a: g4dn.xlarge is offered in 1a and 1c; the game disk is AZ-locked to this one.
  wbox_az          = aws_subnet.subnet_a.availability_zone
  wbox_client_cidr = [for s in local.dev_fleet_subnets : s.cidr_block]
  # Where SSM writes the output of the PowerShell the dev boxes send. The dev roles cannot call
  # ssm:GetCommandInvocation (it has no resource scope and would expose the jumpboxes' command
  # output), so they read the result from here instead: one bucket, one prefix, only wbox writes.
  wbox_output_bucket = "wbox-output-${data.aws_caller_identity.current.account_id}"
  wbox_output_prefix = "wbox"
}

data "aws_ssm_parameter" "wbox_ami" {
  name = "/aws/service/ami-windows-latest/Windows_Server-2025-English-Full-Base"
}

resource "aws_subnet" "wbox" {
  vpc_id                  = local.vpc_id
  cidr_block              = cidrsubnet(data.aws_vpc.selected.cidr_block, 8, 68)
  availability_zone       = local.wbox_az
  map_public_ip_on_launch = false

  tags = { Name = "wbox", Purpose = "windows-playtest" }
}

# Internet and the VPC's implicit local route, nothing else. Never add the I/O box peer route.
resource "aws_route_table" "wbox" {
  vpc_id = local.vpc_id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }

  tags = { Name = "wbox-rt", Purpose = "windows-playtest" }
}

resource "aws_route_table_association" "wbox" {
  subnet_id      = aws_subnet.wbox.id
  route_table_id = aws_route_table.wbox.id
}

resource "aws_security_group" "wbox" {
  name_prefix = "wbox-"
  description = "Windows playtest box: RDP and DCV from the dev fleet subnets only"
  vpc_id      = local.vpc_id

  dynamic "ingress" {
    for_each = { rdp = ["tcp", 3389], dcv-tcp = ["tcp", 8443], dcv-udp = ["udp", 8443] }
    content {
      description = ingress.key
      from_port   = ingress.value[1]
      to_port     = ingress.value[1]
      protocol    = ingress.value[0]
      cidr_blocks = local.wbox_client_cidr
    }
  }

  # Stores, game downloads, Windows Update and online play use many ports; the subnet's
  # route table is what keeps it off the fleet's private peers.
  egress {
    description = "all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "wbox" }

  lifecycle {
    create_before_destroy = true
  }
}

resource "random_password" "wbox_admin" {
  length           = 24
  special          = true
  override_special = "!#%*+-=?@^_"
}

resource "aws_secretsmanager_secret" "wbox_admin" {
  name                    = "wbox/administrator-password"
  description             = "Administrator password of the Windows playtest box (wbox.tf). Generated by Terraform."
  recovery_window_in_days = 7
  tags                    = { Name = "wbox/administrator-password", Purpose = "windows-playtest" }
}

resource "aws_secretsmanager_secret_version" "wbox_admin" {
  secret_id     = aws_secretsmanager_secret.wbox_admin.id
  secret_string = random_password.wbox_admin.result
}

locals {
  wbox_password_readers = [aws_iam_role.wbox.arn, aws_iam_role.dev_server.arn, aws_iam_role.nextjs_dev.arn]
}

resource "aws_secretsmanager_secret_policy" "wbox_admin" {
  secret_arn = aws_secretsmanager_secret.wbox_admin.arn
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "OnlyAdministrationTheBoxAndTheDevBoxesCanRead"
      Effect    = "Deny"
      Principal = "*"
      Action    = "secretsmanager:GetSecretValue"
      Resource  = aws_secretsmanager_secret.wbox_admin.arn
      Condition = { ArnNotLike = { "aws:PrincipalArn" = concat(local.games_mp_admin_principals, local.wbox_password_readers) } }
    }]
  })
}

# The box's own role: Systems Manager (a second way in, and how its setup is checked), the
# NVIDIA driver and DCV license buckets AWS publishes for EC2, and its own password.
resource "aws_iam_role" "wbox" {
  name = "wbox-role"
  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "ec2.amazonaws.com" } }]
  })
  tags = { Name = "wbox-role" }
}

resource "aws_iam_role_policy_attachment" "wbox_ssm" {
  role       = aws_iam_role.wbox.name
  policy_arn = aws_iam_policy.ssm_managed_instance.arn
}

resource "aws_iam_role_policy" "wbox" {
  name = "wbox-setup"
  role = aws_iam_role.wbox.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid      = "NvidiaGridDriver"
        Effect   = "Allow"
        Action   = ["s3:ListBucket", "s3:GetObject"]
        Resource = ["arn:aws:s3:::ec2-windows-nvidia-drivers", "arn:aws:s3:::ec2-windows-nvidia-drivers/*"]
      },
      {
        Sid      = "DcvLicense"
        Effect   = "Allow"
        Action   = "s3:GetObject"
        Resource = "arn:aws:s3:::dcv-license.${var.aws_region}/*"
      },
      {
        Sid      = "OwnAdministratorPassword"
        Effect   = "Allow"
        Action   = "secretsmanager:GetSecretValue"
        Resource = aws_secretsmanager_secret.wbox_admin.arn
      },
      {
        # Run Command uploads its output with the instance's own credentials.
        Sid      = "WriteCommandOutput"
        Effect   = "Allow"
        Action   = "s3:PutObject"
        Resource = "arn:aws:s3:::${local.wbox_output_bucket}/${local.wbox_output_prefix}/*"
      },
    ]
  })
}

resource "aws_iam_instance_profile" "wbox" {
  name = "wbox-profile"
  role = aws_iam_role.wbox.name
}

locals {
  # EBS volumes show up in Windows with the volume id, minus its hyphen, as the disk serial.
  wbox_games_serial = replace(aws_ebs_volume.wbox_games.id, "-", "")

  # Runs at every boot (persist) until one run completes every step; only then is the marker
  # written, so a failure (the password or its grant still propagating, the game disk not yet
  # attached) is retried at the next boot instead of being recorded as done.
  wbox_user_data = <<-PS
<powershell>
$ErrorActionPreference = 'Stop'
Start-Transcript -Path 'C:\wbox-setup.log' -Append
if (Test-Path 'C:\wbox-setup.done') { Stop-Transcript; exit 0 }
try {
  $pw = $null
  for ($i = 0; $i -lt 30 -and -not $pw; $i++) {
    try { $pw = (Get-SECSecretValue -SecretId '${aws_secretsmanager_secret.wbox_admin.name}' -Region '${var.aws_region}').SecretString }
    catch { Start-Sleep -Seconds 10 }
  }
  if (-not $pw) { throw 'could not read the Administrator password' }
  net user Administrator $pw | Out-Null

  # D: is the 100 GB EBS game disk, found by its serial -- never the instance-store NVMe disk,
  # which is wiped at every stop. Its attachment may land after boot: wait for it.
  $serial = '${local.wbox_games_serial}'
  $disk = $null
  for ($i = 0; $i -lt 60 -and -not $disk; $i++) {
    $disk = Get-Disk | Where-Object { $_.SerialNumber -like "$serial*" }
    if (-not $disk) { Start-Sleep -Seconds 10 }
  }
  if (-not $disk) { throw "game disk $serial is not attached" }
  if ($disk.IsOffline) { $disk | Set-Disk -IsOffline $false }
  # Free D: if another volume (the instance store, a DVD) took it.
  $other = Get-Partition -DriveLetter D -ErrorAction SilentlyContinue | Where-Object DiskNumber -ne $disk.Number
  if ($other) {
    $free = [char[]]('EFGHIJKLMNOPQRSTUVWXYZ') | Where-Object { -not (Get-PSDrive -Name $_ -ErrorAction SilentlyContinue) } | Select-Object -First 1
    $other | Set-Partition -NewDriveLetter $free
  }
  if ($disk.PartitionStyle -eq 'RAW') {
    $disk | Initialize-Disk -PartitionStyle GPT -PassThru | New-Partition -DriveLetter D -UseMaximumSize |
      Format-Volume -FileSystem NTFS -NewFileSystemLabel 'Games' -Confirm:$false | Out-Null
  } else {
    # Already formatted (a replaced instance): never reformat, only make sure it is D:.
    $part = $disk | Get-Partition | Where-Object Type -eq 'Basic' | Select-Object -First 1
    if ($part -and $part.DriveLetter -ne 'D') { $part | Set-Partition -NewDriveLetter D }
  }

  $d = 'C:\nvidia'; New-Item -ItemType Directory -Force $d | Out-Null
  Get-S3Object -BucketName 'ec2-windows-nvidia-drivers' -KeyPrefix 'latest/' -Region 'us-east-1' |
    Where-Object Key -like '*.exe' |
    ForEach-Object { Read-S3Object -BucketName $_.BucketName -Key $_.Key -File (Join-Path $d (Split-Path $_.Key -Leaf)) -Region 'us-east-1' | Out-Null }
  $exe = Get-ChildItem $d -Filter *.exe | Select-Object -First 1
  if (-not $exe) { throw 'no NVIDIA driver downloaded' }
  $p = Start-Process $exe.FullName -ArgumentList '-s', '-noreboot', '-clean' -Wait -PassThru
  Write-Output "NVIDIA installer exit code $($p.ExitCode)"
  New-Item -Path 'HKLM:\SOFTWARE\NVIDIA Corporation\Global\GridLicensing' -Force | Out-Null
  New-ItemProperty -Path 'HKLM:\SOFTWARE\NVIDIA Corporation\Global\GridLicensing' -Name 'NvCplDisableManageLicensePage' -PropertyType DWord -Value 1 -Force | Out-Null

  Invoke-WebRequest 'https://d1uj6qtbmh3dt5.cloudfront.net/nice-dcv-server-x64-Release.msi' -OutFile 'C:\dcv.msi'
  $p = Start-Process msiexec -ArgumentList '/i', 'C:\dcv.msi', 'ADDLOCAL=ALL', 'AUTOMATIC_SESSION_OWNER=Administrator', '/quiet', '/norestart' -Wait -PassThru
  if ($p.ExitCode -notin 0, 3010) { throw "DCV install failed: $($p.ExitCode)" }

  Install-WindowsFeature Server-Media-Foundation | Out-Null

  New-Item 'C:\wbox-setup.done' -ItemType File | Out-Null
  Stop-Transcript
  Restart-Computer -Force
} catch {
  Write-Output "wbox setup failed: $_ -- it runs again at the next boot"
  Stop-Transcript
}
</powershell>
<persist>true</persist>
PS
}

resource "aws_instance" "wbox" {
  count = var.enable_wbox ? 1 : 0

  ami                         = nonsensitive(data.aws_ssm_parameter.wbox_ami.value)
  instance_type               = local.wbox_type
  subnet_id                   = aws_subnet.wbox.id
  associate_public_ip_address = true # outbound only: the security group admits the dev boxes alone
  vpc_security_group_ids      = [aws_security_group.wbox.id]
  iam_instance_profile        = aws_iam_instance_profile.wbox.name
  user_data                   = local.wbox_user_data

  root_block_device {
    volume_size = 60
    volume_type = "gp3"
    encrypted   = true
  }

  metadata_options {
    http_tokens = "required"
  }

  # A new Windows AMI or setup script must not replace a box with a game installed on it.
  lifecycle {
    ignore_changes = [ami, user_data]
  }

  # First boot reads the password with this role: both must exist before Windows starts.
  depends_on = [
    aws_secretsmanager_secret_version.wbox_admin,
    aws_secretsmanager_secret_policy.wbox_admin,
    aws_iam_role_policy.wbox,
    aws_iam_role_policy_attachment.wbox_ssm,
  ]

  tags = { Name = local.wbox_name, Purpose = "windows-playtest" }
}

resource "aws_ebs_volume" "wbox_games" {
  availability_zone = local.wbox_az
  size              = 100
  type              = "gp3"
  encrypted         = true
  tags              = { Name = "wbox-games", Purpose = "windows-playtest" }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_volume_attachment" "wbox_games" {
  count = var.enable_wbox ? 1 : 0

  device_name                    = "xvdf"
  volume_id                      = aws_ebs_volume.wbox_games.id
  instance_id                    = aws_instance.wbox[0].id
  stop_instance_before_detaching = true
}

# Output of the PowerShell the dev boxes send (see wbox_output_bucket above): private, encrypted, a week.
resource "aws_s3_bucket" "wbox_output" {
  bucket        = local.wbox_output_bucket
  force_destroy = true # scratch: command output only, expired after a week
  tags          = { Name = local.wbox_output_bucket }
}

resource "aws_s3_bucket_public_access_block" "wbox_output" {
  bucket                  = aws_s3_bucket.wbox_output.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "wbox_output" {
  bucket = aws_s3_bucket.wbox_output.id
  rule {
    apply_server_side_encryption_by_default { sse_algorithm = "AES256" }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "wbox_output" {
  bucket = aws_s3_bucket.wbox_output.id
  rule {
    id     = "expire-command-output"
    status = "Enabled"
    filter {}
    expiration { days = 7 }
  }
}

# The dev boxes: start, stop and reboot this one instance, send it PowerShell, and read its password
# and the output.
data "aws_iam_policy_document" "wbox_control" {
  count = var.enable_wbox ? 1 : 0

  statement {
    sid       = "StartStopTheWindowsBox"
    actions   = ["ec2:StartInstances", "ec2:StopInstances", "ec2:RebootInstances"]
    resources = [aws_instance.wbox[0].arn]
  }

  statement {
    sid       = "ReadItsPassword"
    actions   = ["secretsmanager:GetSecretValue"]
    resources = [aws_secretsmanager_secret.wbox_admin.arn]
  }

  # Run PowerShell on this one box through Systems Manager (install a store, check a game),
  # the way an admin does: the instance, the one AWS document and the one output bucket, nothing
  # else. SendCommand authorizes the output bucket as a resource, so a caller cannot send the
  # output anywhere but here. The target is the Windows box, never a jumpbox (AGENTS.md: dev ->
  # jumpbox is not permitted).
  statement {
    sid     = "RunPowerShellOnTheWindowsBox"
    actions = ["ssm:SendCommand"]
    resources = [
      aws_instance.wbox[0].arn,
      "arn:aws:ssm:${var.aws_region}::document/AWS-RunPowerShellScript",
      aws_s3_bucket.wbox_output.arn,
    ]
  }

  # Deliberately NO ssm:GetCommandInvocation / ListCommands / ListCommandInvocations: they have no
  # resource-level authorization, so they would expose the jumpboxes' command output to a dev box,
  # and dev-instance-common.tf denies them on purpose (NeverReadAccountWideCommandOutput). The
  # result is read from the output bucket instead.
  statement {
    sid       = "ReadCommandOutput"
    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.wbox_output.arn}/${local.wbox_output_prefix}/*"]
  }

  statement {
    sid       = "ListCommandOutput"
    actions   = ["s3:ListBucket"]
    resources = [aws_s3_bucket.wbox_output.arn]
    condition {
      test     = "StringLike"
      variable = "s3:prefix"
      values   = ["${local.wbox_output_prefix}/*"]
    }
  }
}

resource "aws_iam_policy" "wbox_control" {
  count = var.enable_wbox ? 1 : 0

  name        = "wbox-control"
  description = "Dev boxes: start, stop, reboot and run PowerShell (SSM, output via S3) on the Windows playtest box, and read its password"
  policy      = data.aws_iam_policy_document.wbox_control[0].json
}

resource "aws_iam_role_policy_attachment" "wbox_control" {
  for_each   = var.enable_wbox ? { dev_server = aws_iam_role.dev_server.name, nextjs_dev = aws_iam_role.nextjs_dev.name } : {}
  role       = each.value
  policy_arn = aws_iam_policy.wbox_control[0].arn
}

output "wbox_private_ip" {
  description = "The Windows playtest box, reachable from the dev boxes only: https://<ip>:8443 (DCV) or RDP <ip>:3389"
  value       = var.enable_wbox ? aws_instance.wbox[0].private_ip : null
}

# One hour idle, then stop: the dev-auto-stop code (dev-auto-stop-lambda.tf) with its own
# settings, checked every 10 minutes so a finished session stops about an hour later. It only
# counts CPU since the instance last started, so a fresh `wbox up` is never stopped at once.
resource "aws_lambda_function" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  function_name = "wbox-auto-stop"
  role          = aws_iam_role.dev_auto_stop.arn
  handler       = "index.lambda_handler"
  runtime       = "python3.12"
  timeout       = 60
  memory_size   = 128

  filename         = data.archive_file.dev_auto_stop.output_path
  source_code_hash = data.archive_file.dev_auto_stop.output_base64sha256

  environment {
    variables = {
      INSTANCE_IDS  = aws_instance.wbox[0].id
      SNS_TOPIC_ARN = aws_sns_topic.cost_alerts.arn
      SNS_REGION    = var.aws_region
      IDLE_HOURS    = "1"
      # Idle Windows plus the DCV agent measured 6.4% average and 11.7% peak for 30 hours straight (2026-10-03), so the
      # default 5% could never see it as idle and it ran 4+ days at about $20/day. A real session (a game streaming)
      # sits far above 15.
      CPU_THRESHOLD = "15"
    }
  }

  tags = { Name = "wbox-auto-stop" }
}

resource "aws_cloudwatch_event_rule" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  name                = "wbox-auto-stop"
  description         = "Stop the Windows playtest box after one hour below 5% CPU"
  schedule_expression = "rate(10 minutes)"

  tags = { Name = "wbox-auto-stop" }
}

resource "aws_cloudwatch_event_target" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  rule      = aws_cloudwatch_event_rule.wbox_auto_stop[0].name
  target_id = "wbox-auto-stop-lambda"
  arn       = aws_lambda_function.wbox_auto_stop[0].arn
}

resource "aws_lambda_permission" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  statement_id  = "AllowEventBridge"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.wbox_auto_stop[0].function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.wbox_auto_stop[0].arn
}
