# wbox.tf
#
# THE WINDOWS BOX: one Windows Server 2025 instance with an NVIDIA GPU, for playtesting
# Windows games (first: Age of Empires I: Definitive Edition from the Microsoft Store, which
# needs the Xbox app and has no cloud-streaming version).
#
# PERSISTENT, unlike the GPU test box (gpu-box.tf): an installed game, its store login and
# its saves must survive, so terraform owns the instance and a separate 100 GB game disk
# (D:), and the dev boxes STOP and START it (`wbox up` / `wbox down`, scripts/wbox.sh) with
# a grant scoped to this one instance. Stopped, it costs only its disks (~$13/month);
# running, g4dn.xlarge with Windows is ~$0.82/hour in us-west-1. Its own copy of the
# dev-auto-stop Lambda (below) stops it after ONE hour below 5% CPU, checked every 10 minutes.
#
# REACHABLE ONLY FROM THE DEV BOXES (the perimeter rule: nothing new listens on the
# internet). Its security group admits RDP (3389) and Amazon DCV (8443, TCP and UDP) from
# the dev fleet's subnets only, so a player reaches it through a dev box: DCV's web client in
# a dev box's browser (the browser-manager desktops on fcvm-metal-arm), or a tunnel over the
# SSH already allowed, `ssh -L 8443:<wbox private IP>:8443 fcvm-arm`. It has its own subnet
# whose route table has the internet and nothing else -- no I/O-box peer route -- so a
# Windows desktop that runs downloaded games cannot reach the fleet's NFS scratch.
#
# FIRST BOOT (user_data, once): sets the Administrator password from Secrets Manager
# (wbox/administrator-password, generated here; the dev roles may read it), formats D: only
# if it is RAW, installs the NVIDIA GRID driver from AWS's bucket, Amazon DCV and Media
# Foundation, then reboots. The store and game installs are the player's.

variable "enable_wbox" {
  description = "Create the Windows playtest box (wbox.tf). The game disk has prevent_destroy either way."
  type        = bool
  default     = true
}

locals {
  wbox_name = "wbox"
  wbox_type = "g4dn.xlarge"
  # us-west-1a: g4dn.xlarge is offered in 1a and 1c; the game disk is AZ-locked to this one.
  wbox_az          = aws_subnet.subnet_a.availability_zone
  wbox_client_cidr = [for s in local.dev_fleet_subnets : s.cidr_block]
}

data "aws_ssm_parameter" "wbox_ami" {
  name = "/aws/service/ami-windows-latest/Windows_Server-2025-English-Full-Base"
}

resource "aws_subnet" "wbox" {
  vpc_id                  = local.vpc_id
  cidr_block              = cidrsubnet(data.aws_vpc.selected.cidr_block, 8, 68)
  availability_zone       = local.wbox_az
  map_public_ip_on_launch = false

  tags = { Name = "wbox", Purpose = "windows-playtest" }
}

# Internet and the VPC's implicit local route, nothing else. Never add the I/O box peer route.
resource "aws_route_table" "wbox" {
  vpc_id = local.vpc_id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }

  tags = { Name = "wbox-rt", Purpose = "windows-playtest" }
}

resource "aws_route_table_association" "wbox" {
  subnet_id      = aws_subnet.wbox.id
  route_table_id = aws_route_table.wbox.id
}

resource "aws_security_group" "wbox" {
  name_prefix = "wbox-"
  description = "Windows playtest box: RDP and DCV from the dev fleet subnets only"
  vpc_id      = local.vpc_id

  dynamic "ingress" {
    for_each = { rdp = ["tcp", 3389], dcv-tcp = ["tcp", 8443], dcv-udp = ["udp", 8443] }
    content {
      description = ingress.key
      from_port   = ingress.value[1]
      to_port     = ingress.value[1]
      protocol    = ingress.value[0]
      cidr_blocks = local.wbox_client_cidr
    }
  }

  # Stores, game downloads, Windows Update and online play use many ports; the subnet's
  # route table is what keeps it off the fleet's private peers.
  egress {
    description = "all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "wbox" }

  lifecycle {
    create_before_destroy = true
  }
}

resource "random_password" "wbox_admin" {
  length           = 24
  special          = true
  override_special = "!#%*+-=?@^_"
}

resource "aws_secretsmanager_secret" "wbox_admin" {
  name                    = "wbox/administrator-password"
  description             = "Administrator password of the Windows playtest box (wbox.tf). Generated by Terraform."
  recovery_window_in_days = 7
  tags                    = { Name = "wbox/administrator-password", Purpose = "windows-playtest" }
}

resource "aws_secretsmanager_secret_version" "wbox_admin" {
  secret_id     = aws_secretsmanager_secret.wbox_admin.id
  secret_string = random_password.wbox_admin.result
}

locals {
  wbox_password_readers = [aws_iam_role.wbox.arn, aws_iam_role.dev_server.arn, aws_iam_role.nextjs_dev.arn]
}

resource "aws_secretsmanager_secret_policy" "wbox_admin" {
  secret_arn = aws_secretsmanager_secret.wbox_admin.arn
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "OnlyAdministrationTheBoxAndTheDevBoxesCanRead"
      Effect    = "Deny"
      Principal = "*"
      Action    = "secretsmanager:GetSecretValue"
      Resource  = aws_secretsmanager_secret.wbox_admin.arn
      Condition = { ArnNotLike = { "aws:PrincipalArn" = concat(local.games_mp_admin_principals, local.wbox_password_readers) } }
    }]
  })
}

# The box's own role: Systems Manager (a second way in, and how its setup is checked), the
# NVIDIA driver and DCV license buckets AWS publishes for EC2, and its own password.
resource "aws_iam_role" "wbox" {
  name = "wbox-role"
  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "ec2.amazonaws.com" } }]
  })
  tags = { Name = "wbox-role" }
}

resource "aws_iam_role_policy_attachment" "wbox_ssm" {
  role       = aws_iam_role.wbox.name
  policy_arn = aws_iam_policy.ssm_managed_instance.arn
}

resource "aws_iam_role_policy" "wbox" {
  name = "wbox-setup"
  role = aws_iam_role.wbox.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid      = "NvidiaGridDriver"
        Effect   = "Allow"
        Action   = ["s3:ListBucket", "s3:GetObject"]
        Resource = ["arn:aws:s3:::ec2-windows-nvidia-drivers", "arn:aws:s3:::ec2-windows-nvidia-drivers/*"]
      },
      {
        Sid      = "DcvLicense"
        Effect   = "Allow"
        Action   = "s3:GetObject"
        Resource = "arn:aws:s3:::dcv-license.${var.aws_region}/*"
      },
      {
        Sid      = "OwnAdministratorPassword"
        Effect   = "Allow"
        Action   = "secretsmanager:GetSecretValue"
        Resource = aws_secretsmanager_secret.wbox_admin.arn
      },
    ]
  })
}

resource "aws_iam_instance_profile" "wbox" {
  name = "wbox-profile"
  role = aws_iam_role.wbox.name
}

locals {
  wbox_user_data = <<-PS
<powershell>
$ErrorActionPreference = 'Continue'
Start-Transcript -Path 'C:\wbox-setup.log' -Append
if (-not (Test-Path 'C:\wbox-setup.done')) {
  $pw = (Get-SECSecretValue -SecretId '${aws_secretsmanager_secret.wbox_admin.name}' -Region '${var.aws_region}').SecretString
  net user Administrator $pw | Out-Null
  # D: is the persistent game disk. Only a RAW disk is initialized: never a formatted one.
  Get-Disk | Where-Object PartitionStyle -eq 'RAW' | Initialize-Disk -PartitionStyle GPT -PassThru |
    New-Partition -DriveLetter D -UseMaximumSize | Format-Volume -FileSystem NTFS -NewFileSystemLabel 'Games' -Confirm:$false
  $d = 'C:\nvidia'; New-Item -ItemType Directory -Force $d | Out-Null
  Get-S3Object -BucketName 'ec2-windows-nvidia-drivers' -KeyPrefix 'latest/' -Region 'us-east-1' |
    Where-Object Key -like '*.exe' |
    ForEach-Object { Read-S3Object -BucketName $_.BucketName -Key $_.Key -File (Join-Path $d (Split-Path $_.Key -Leaf)) -Region 'us-east-1' }
  Get-ChildItem $d -Filter *.exe | ForEach-Object { Start-Process $_.FullName -ArgumentList '-s', '-noreboot', '-clean' -Wait }
  New-Item -Path 'HKLM:\SOFTWARE\NVIDIA Corporation\Global\GridLicensing' -Force | Out-Null
  New-ItemProperty -Path 'HKLM:\SOFTWARE\NVIDIA Corporation\Global\GridLicensing' -Name 'NvCplDisableManageLicensePage' -PropertyType DWord -Value 1 -Force | Out-Null
  Invoke-WebRequest 'https://d1uj6qtbmh3dt5.cloudfront.net/nice-dcv-server-x64-Release.msi' -OutFile 'C:\dcv.msi'
  Start-Process msiexec -ArgumentList '/i', 'C:\dcv.msi', 'ADDLOCAL=ALL', 'AUTOMATIC_SESSION_OWNER=Administrator', '/quiet', '/norestart' -Wait
  Install-WindowsFeature Server-Media-Foundation | Out-Null
  New-Item 'C:\wbox-setup.done' -ItemType File | Out-Null
  Stop-Transcript
  Restart-Computer -Force
}
</powershell>
PS
}

resource "aws_instance" "wbox" {
  count = var.enable_wbox ? 1 : 0

  ami                         = nonsensitive(data.aws_ssm_parameter.wbox_ami.value)
  instance_type               = local.wbox_type
  subnet_id                   = aws_subnet.wbox.id
  associate_public_ip_address = true # outbound only: the security group admits the dev boxes alone
  vpc_security_group_ids      = [aws_security_group.wbox.id]
  iam_instance_profile        = aws_iam_instance_profile.wbox.name
  user_data                   = local.wbox_user_data

  root_block_device {
    volume_size = 60
    volume_type = "gp3"
    encrypted   = true
  }

  metadata_options {
    http_tokens = "required"
  }

  # A new Windows AMI or setup script must not replace a box with a game installed on it.
  lifecycle {
    ignore_changes = [ami, user_data]
  }

  tags = { Name = local.wbox_name, Purpose = "windows-playtest" }
}

resource "aws_ebs_volume" "wbox_games" {
  availability_zone = local.wbox_az
  size              = 100
  type              = "gp3"
  encrypted         = true
  tags              = { Name = "wbox-games", Purpose = "windows-playtest" }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_volume_attachment" "wbox_games" {
  count = var.enable_wbox ? 1 : 0

  device_name                    = "xvdf"
  volume_id                      = aws_ebs_volume.wbox_games.id
  instance_id                    = aws_instance.wbox[0].id
  stop_instance_before_detaching = true
}

# The dev boxes: start, stop and reboot this one instance, and read its password.
data "aws_iam_policy_document" "wbox_control" {
  count = var.enable_wbox ? 1 : 0

  statement {
    sid       = "StartStopTheWindowsBox"
    actions   = ["ec2:StartInstances", "ec2:StopInstances", "ec2:RebootInstances"]
    resources = [aws_instance.wbox[0].arn]
  }

  statement {
    sid       = "ReadItsPassword"
    actions   = ["secretsmanager:GetSecretValue"]
    resources = [aws_secretsmanager_secret.wbox_admin.arn]
  }
}

resource "aws_iam_policy" "wbox_control" {
  count = var.enable_wbox ? 1 : 0

  name        = "wbox-control"
  description = "Dev boxes: start, stop and reboot the Windows playtest box and read its password"
  policy      = data.aws_iam_policy_document.wbox_control[0].json
}

resource "aws_iam_role_policy_attachment" "wbox_control" {
  for_each   = var.enable_wbox ? { dev_server = aws_iam_role.dev_server.name, nextjs_dev = aws_iam_role.nextjs_dev.name } : {}
  role       = each.value
  policy_arn = aws_iam_policy.wbox_control[0].arn
}

output "wbox_private_ip" {
  description = "The Windows playtest box, reachable from the dev boxes only: https://<ip>:8443 (DCV) or RDP <ip>:3389"
  value       = var.enable_wbox ? aws_instance.wbox[0].private_ip : null
}

# One hour idle, then stop: the dev-auto-stop code (dev-auto-stop-lambda.tf) with its own
# settings, checked every 10 minutes so a finished session stops about an hour later. It only
# counts CPU since the instance last started, so a fresh `wbox up` is never stopped at once.
resource "aws_lambda_function" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  function_name = "wbox-auto-stop"
  role          = aws_iam_role.dev_auto_stop.arn
  handler       = "index.lambda_handler"
  runtime       = "python3.12"
  timeout       = 60
  memory_size   = 128

  filename         = data.archive_file.dev_auto_stop.output_path
  source_code_hash = data.archive_file.dev_auto_stop.output_base64sha256

  environment {
    variables = {
      INSTANCE_IDS  = aws_instance.wbox[0].id
      SNS_TOPIC_ARN = aws_sns_topic.cost_alerts.arn
      SNS_REGION    = var.aws_region
      IDLE_HOURS    = "1"
    }
  }

  tags = { Name = "wbox-auto-stop" }
}

resource "aws_cloudwatch_event_rule" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  name                = "wbox-auto-stop"
  description         = "Stop the Windows playtest box after one hour below 5% CPU"
  schedule_expression = "rate(10 minutes)"

  tags = { Name = "wbox-auto-stop" }
}

resource "aws_cloudwatch_event_target" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  rule      = aws_cloudwatch_event_rule.wbox_auto_stop[0].name
  target_id = "wbox-auto-stop-lambda"
  arn       = aws_lambda_function.wbox_auto_stop[0].arn
}

resource "aws_lambda_permission" "wbox_auto_stop" {
  count = var.enable_wbox ? 1 : 0

  statement_id  = "AllowEventBridge"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.wbox_auto_stop[0].function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.wbox_auto_stop[0].arn
}
